### ISSUE TITLE
Command must return integer to be compatible with Symfony 5.0

### ISSUE THREAD

**Issue by JakeFr** [a-r-m-i-n/scssphp-bundle#1]
Symfony 5 enforces commands to return integer

` #message: "Return value of "Armin\ScssphpBundle\Command\CompileCommand::execute()" must be of the type int, NULL returned."`

A `return 0;` statement is missing at the end of CompileCommand.
And statements `return;` when aborting command must be change to `return 1;`

**Comment by a-r-m-i-n** [comment]
Thanks for reporting and sorry for the extreme long delay. I've fixed it and released it in version 1.1.2.
